services:
  postgres:
    image: postgres:16.0
    container_name: drizzle-postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
## Inicializar docker : docker-compose --env-file ../.env up -d